common:
  cli:
    - Git.Git
    - JanDeDobbeleer.OhMyPosh

macos:
  brew:
    - git
    - gh

  gui:
    - google-chrome
    - firefox
    - visual-studio-code
    - bitwarden

windows:
  winget:
    - Git.Git
    - GitHub.cli

  gui:
    - Google.Chrome
    - Mozilla.Firefox
    - Microsoft.VisualStudioCode
    - Bitwarden.Bitwarden
    - Google.JapaneseInput

profiles:
  work:
    macos:
      brew:
        - awscli
    windows:
      winget:
        - Amazon.AWSCLI
  personal:
    macos:
      brew:
        - mas
    windows:
      winget:
        - Microsoft.PowerToys
